name: pre-release 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., alpha-v0.0.2)'
        required: true
      version-number:
        description: 'Release version number (e.g., 1.0.0)'
        required: true

jobs:
  pre-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Build resources
      run: npm run build

    - name: Build with electron-builder
      uses: samuelmeuli/action-electron-builder@v1
      with:
        github_token: ${{ secrets.github_token }}
        release: false
        args: -c.extraMetadata.version=${{ github.event.inputs.version-number }}

    - name: Create Pre-Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ github.event.inputs.version }}"
        prerelease: true
        title: "Pre-Release ${{ github.event.inputs.version }}"
        files: |
          dist/*.exe
          dist/*.AppImage
          dist/*.deb